# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 09:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokengenerator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='token',
        ),
    ]
