# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokengenerator', '0002_auto_20181125_0940'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Tokenpool',
        ),
    ]
