# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokengenerator', '0003_auto_20181125_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpool',
            name='alive',
            field=models.IntegerField(default='Alive', max_length=1),
        ),
    ]
