# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-25 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokengenerator', '0004_auto_20181125_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenpool',
            name='alive',
            field=models.CharField(default='Alive', max_length=15),
        ),
    ]
